dk_zips = {
    '2460': '', # This zip code is invalid; might have been a typo, could have been '3460' (2460 is a Norwegian zip code)
    '4736': 'Region Sjælland',
    '5700': 'Region Syddanmark',
    '6200': 'Region Syddanmark',
    '6894': '', # This zip code is invalid; might have been a typo
    '8420': 'Region Midtjylland',
    '9240': 'Region Nordjylland',
    }

uk_zips = {
    'AB32': 'Scotland',
    'AL6': 'East of England',
    'b8': 'West Midlands',
    'B93': 'West Midlands',
    'BA2': 'South West',
    'de74  3ef': 'East Midlands',
    'Bd151de': 'Yorkshire and The Humber',
    'BD7': 'Yorkshire and The Humber',
    'BL8': 'North West',
    'bl9': 'North West',
    'bn15': 'South East',
    'BR5': 'London',
    'BR6': 'London',
    'BS4': 'South West',
    'bs6': 'South West',
    'BT13': 'Northern Ireland',
    'BT27': 'Northern Ireland',
    'bt32': 'Northern Ireland',
    'CB24': 'East of England',
    'CH42 0AD': 'North West',
    'CH44': 'North West',
    'CM21': 'East of England',
    'CT12': 'South East',
    'CT2': 'South East',
    'CT6': 'South East',
    'de74 3ef': 'East Midlands',
    'dh1': 'North East',
    'DN18': 'Yorkshire and The Humber',
    'dn3': 'Yorkshire and The Humber',
    'DY7': 'West Midlands',
    'E12': 'London',
    'e20': 'London',
    'EC1N': 'London',
    'EH4': 'Scotland',
    'g76': 'Scotland',
    'Gu1': 'South East',
    'IP10': 'East of England',
    'KT18': 'South East',
    'KT3 8DJ': 'South East',
    'L23': 'North West',
    'L35': 'North West',
    'L36': 'North West',
    'L4': 'North West',
    'L5': 'North West',
    'le18': 'East Midlands',
    'LE9': 'East Midlands',
    'LN4': 'East Midlands',
    'LS23': 'Yorkshire and The Humber',
    'M1': 'North West',
    'M16': 'North West',
    'm20': 'North West',
    'M44': 'North West',
    'ME10': 'South East',
    'ML11': 'Scotland',
    'NE36': 'North East',
    'NG6': 'East Midlands',
    'NN10': 'East Midlands',
    'NR3': 'East of England',
    'NR33 8': 'East of England',
    'OL4': 'North West',
    'OX14 5': 'South East',
    'ox16': 'South East',
    'OX18': 'South East',
    'ox4': 'South East',
    'pe30': 'East of England',
    'PL4': 'South West',
    'po33': 'South East',
    'PR4': 'North West',
    'Pr8': 'North West',
    'RG19': 'South East',
    'S72': 'Yorkshire and The Humber',
    'se25': 'London',
    'Se9': 'London',
    'SE9': 'London',
    'SN12': 'South West',
    'SO17': 'South East',
    'SO30': 'South East',
    'SW20': 'London',
    'TA1 8ND': 'South West',
    'TN1': 'South East',
    'tn14': 'South East',
    'TR2': 'South West',
    'Tr6': 'South West',
    'tw7': 'London',
    'ub5': 'London',
    'Ws12': 'West Midlands',
    'ws9': 'West Midlands',
    'YO11': 'Yorkshire and The Humber',
    'YO24': 'Yorkshire and The Humber'
    }

us_zips = {
    '.30310': 'South',
    '46728': 'Midwest',
    '41015': 'South',
    '186': '', # This zip code is invalid; Not enough information to determine region (could potentially be PA or MA)
    }